# Generated by Django 5.1.7 on 2026-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст обращения')),
                ('contact', models.CharField(blank=True, help_text='Телефон или почта, если оставили', max_length=200, verbose_name='Как связаться')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Когда пришло')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Письмо директору',
                'verbose_name_plural': 'Письма директору',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('product', models.CharField(blank=True, max_length=120, verbose_name='Что нужно')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='Объём и адрес')),
                ('page', models.CharField(blank=True, help_text='С какой страницы отправлена заявка', max_length=200, verbose_name='Страница')),
                ('utm', models.CharField(blank=True, max_length=300, verbose_name='Метки кампании')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('done', 'Обработана'), ('spam', 'Спам')], default='new', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Когда пришла')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created'],
            },
        ),
    ]
