# Generated by Django 5.1.7 on 2026-09-29 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('word', 'Word'), ('pdf', 'PDF'), ('excel', 'Excel'), ('other', 'Файл')], default='pdf', max_length=10, verbose_name='Тип файла')),
                ('file', models.FileField(blank=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'rtf'])], verbose_name='Файл')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Имя URL — менять не нужно', max_length=60, unique=True, verbose_name='Маршрут')),
                ('admin_title', models.CharField(help_text='Как называется в этом списке', max_length=120, verbose_name='Страница')),
                ('h1', models.CharField(blank=True, help_text='Можно с разметкой: <br> — перенос, <em> — выделение цветом', max_length=250, verbose_name='Заголовок на странице (H1)')),
                ('stamp', models.CharField(blank=True, help_text='Мелкая подпись со штрихом слева', max_length=150, verbose_name='Надпись над заголовком')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('body', models.TextField(blank=True, help_text='Для текстовых страниц — политика конфиденциальности. Можно с HTML', verbose_name='Основной текст')),
                ('photo', models.ImageField(blank=True, help_text='Фон шапки страницы. Если пусто — берётся фото из вёрстки', upload_to='pages/', verbose_name='Фото в шапке')),
                ('seo_title', models.CharField(blank=True, help_text='Если пусто — берётся заголовок страницы', max_length=250, verbose_name='SEO-заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=400, verbose_name='SEO-описание (description)')),
            ],
            options={
                'verbose_name': 'Страница (тексты и SEO)',
                'verbose_name_plural': 'Страницы (тексты и SEO)',
                'ordering': ['admin_title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_main', models.CharField(default='+7 928 821-72-11', max_length=40, verbose_name='Телефон отдела продаж')),
                ('phone_extra', models.CharField(blank=True, default='+7 928 821-72-02', max_length=40, verbose_name='Второй телефон')),
                ('phone_note', models.CharField(blank=True, default='Отдел продаж · пн–сб', max_length=100, verbose_name='Подпись под телефоном')),
                ('address', models.CharField(default='Пятигорск, Черкесское шоссе, 2', max_length=250, verbose_name='Адрес')),
                ('address_full', models.CharField(blank=True, default='357522, Ставропольский край, город Пятигорск, Черкесское шоссе, 2 (промзона)', max_length=300, verbose_name='Адрес полностью')),
                ('work_hours', models.CharField(default='пн–сб, 8:00–16:30', max_length=120, verbose_name='Режим работы')),
                ('map_lat', models.CharField(default='44.053091', max_length=20, verbose_name='Широта')),
                ('map_lon', models.CharField(default='42.993845', max_length=20, verbose_name='Долгота')),
                ('map_zoom', models.PositiveSmallIntegerField(default=16, verbose_name='Масштаб карты')),
                ('company', models.CharField(default='ЗАО «Стройдеталь-2»', max_length=150, verbose_name='Название организации')),
                ('founded_year', models.CharField(default='1962', max_length=10, verbose_name='Год основания')),
                ('lead_emails', models.CharField(blank=True, help_text='Адреса через запятую — на них уходит письмо о каждой заявке', max_length=300, verbose_name='Куда слать заявки')),
                ('director_email', models.EmailField(blank=True, help_text='Форма «написать директору» уходит только сюда, минуя отдел продаж', max_length=254, verbose_name='Личная почта директора')),
                ('noindex', models.BooleanField(default=True, help_text='Включено — robots.txt запрещает обход, в страницах стоит noindex. Снять в день переезда на рабочий домен', verbose_name='Закрыть сайт от индексации')),
                ('metrika_id', models.CharField(blank=True, help_text='Пусто — счётчик не подключается', max_length=20, verbose_name='Номер счётчика Яндекс.Метрики')),
                ('show_prices', models.BooleanField(default=True, help_text='Выключено — вместо всех цен на сайте будет «по запросу». У позиции цену можно убрать и по отдельности, очистив поле', verbose_name='Показывать цены')),
                ('price_note', models.CharField(blank=True, default='Цены ориентировочные, зависят от объёма партии', help_text='Показывается под таблицами с ценами', max_length=200, verbose_name='Приписка к ценам')),
            ],
            options={
                'verbose_name': 'Общие данные сайта',
                'verbose_name_plural': 'Общие данные сайта',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('url_name', models.CharField(blank=True, help_text='Имя URL, например produkciya_beton', max_length=60, verbose_name='Маршрут')),
                ('anchor', models.CharField(blank=True, help_text='Если пункт ведёт на блок страницы, например products', max_length=40, verbose_name='Якорь')),
                ('in_footer', models.BooleanField(default=False, verbose_name='Показывать в подвале')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('section', models.CharField(default='main', help_text='Ключ блока — тот же, что у заголовка блока', max_length=60, verbose_name='Блок на странице')),
                ('icon', models.CharField(blank=True, help_text='Короткая подпись сверху: 01, «Шаг 01», «Зона»', max_length=40, verbose_name='Индекс или тег')),
                ('value', models.CharField(blank=True, help_text='Для плиток с цифрой, например 10–15 или ×2,5', max_length=30, verbose_name='Крупное значение')),
                ('sup', models.CharField(blank=True, help_text='Мелкий текст рядом с цифрой: %, литров, часов', max_length=30, verbose_name='Приписка к значению')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, help_text='Для плиток с местом под фото', upload_to='cards/', verbose_name='Фото')),
                ('url_name', models.CharField(blank=True, help_text='Имя URL, если плитка ведёт на страницу', max_length=60, verbose_name='Маршрут ссылки')),
                ('anchor', models.CharField(blank=True, help_text='Например request — форма заявки', max_length=40, verbose_name='Якорь ссылки')),
                ('link_label', models.CharField(blank=True, max_length=100, verbose_name='Подпись ссылки')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Плитка в блоке',
                'verbose_name_plural': 'Плитки в блоках',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('key', models.CharField(help_text='Совпадает с якорем в вёрстке, например price. Не менять', max_length=60, verbose_name='Ключ блока')),
                ('stamp', models.CharField(blank=True, help_text='Мелкая подпись со штрихом слева, например «Честно про цену»', max_length=150, verbose_name='Надпись над заголовком')),
                ('title', models.CharField(blank=True, help_text='Можно с разметкой: <br> — перенос строки', max_length=250, verbose_name='Заголовок')),
                ('lead', models.TextField(blank=True, help_text='Абзац справа от заголовка', verbose_name='Вводный текст')),
                ('note', models.TextField(blank=True, help_text='Мелкий текст после таблицы или сетки', verbose_name='Примечание под блоком')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страниц',
                'ordering': ['order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_section_key')],
            },
        ),
    ]
