# Generated by Django 5.1.7 on 2026-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='photo',
            field=models.ImageField(blank=True, help_text='Для блоков со снимком сбоку или на фоне. Пусто — останется фото из вёрстки', upload_to='sections/', verbose_name='Фото блока'),
        ),
        migrations.AddField(
            model_name='section',
            name='photo_caption',
            field=models.CharField(blank=True, help_text='Синяя плашка в углу снимка', max_length=200, verbose_name='Подпись к фото'),
        ),
    ]
