# Generated by Django 5.1.7 on 2026-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhbigroup',
            name='custom_template',
            field=models.CharField(blank=True, help_text='Для групп с особой вёрсткой — например плитка с моделями и цветами. Пусто — обычная таблица характеристик', max_length=60, verbose_name='Свой шаблон'),
        ),
    ]
