# Generated by Django 5.1.7 on 2026-09-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=200, verbose_name='Что сертифицировано')),
                ('gost', models.CharField(blank=True, max_length=120, verbose_name='ГОСТ')),
                ('scan', models.ImageField(upload_to='certs/', verbose_name='Скан')),
                ('thumb', models.ImageField(blank=True, help_text='Уменьшенная копия для плитки. Пусто — возьмём скан', upload_to='certs/', verbose_name='Миниатюра')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='partners/', verbose_name='Логотип')),
                ('caption', models.CharField(blank=True, help_text='Что поставляет: «Бетонные заводы». Перенос строки — <br>', max_length=120, verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('category', models.CharField(help_text='Торговая недвижимость, жильё, инфраструктура', max_length=100, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('is_greenhouse', models.BooleanField(default=False, help_text='Показывать в блоке тепличных комплексов, а не в общем реестре объектов', verbose_name='Тепличный комплекс')),
                ('text', models.TextField(blank=True, help_text='Только для тепличных комплексов', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=150, verbose_name='Имя и фамилия')),
                ('full_name', models.CharField(blank=True, help_text='Строка под именем, например «Михаил Алексеевич»', max_length=150, verbose_name='Имя и отчество')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('note', models.CharField(blank=True, help_text='Чем занимается: «бетон, раствор, ЖБИ»', max_length=200, verbose_name='Уточнение')),
                ('photo', models.ImageField(blank=True, help_text='Портрет 3:4. Если пусто — заглушка «фото уточняется»', upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('year', models.CharField(max_length=20, verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Что произошло')),
                ('text', models.TextField(blank=True, verbose_name='Подробнее')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'История завода',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Участок')),
                ('weekdays', models.CharField(help_text='8:00 — 16:30', max_length=120, verbose_name='Понедельник — суббота')),
                ('sunday', models.CharField(blank=True, default='Выходной', max_length=60, verbose_name='Воскресенье')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Режим работы участка',
                'verbose_name_plural': 'Режим работы участков',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('number', models.CharField(max_length=40, verbose_name='Телефон')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='content.teammember', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Телефон сотрудника',
                'verbose_name_plural': 'Телефоны сотрудников',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
